### PR TITLE
Fix #541: Support primary keys other then :id on model classes

### LINKED ISSUE #541: custom primary_key not supported on model -- fails on i18n.find_by
## Context
I want to translate a model (let's say `Article`) which has a primary key other than `id`, let's say `article_id` for example.

## Expected Behavior
When calling `Article.i18n.find_by(title: 'foo')`
The article with title "foo" is returned

## Actual Behavior

An error is thrown:

`ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column article.id does not exist`

## Possible Fix

See https://github.com/benjamin-hg/mobility/commit/5939dd3adcb9b595f90c1f5e7a340e7ef1bca099

### PR DESCRIPTION
**Pull request by benjamin-hg**
Fixes #541

### CODE REVIEW

**Comment by shioyama** [comment]
Oh very nice, super clean fix! Thanks :heart: Once specs pass I'll merge this.

**Comment by benjamin-hg** [comment]
Hi @shioyama, when can I expect this to go into a release?

**Comment by shioyama** [comment]
Ah this would go into 1.3. Just need to cut a release, maybe in the next few weeks or so?

**Comment by benjamin-hg** [comment]
Hi @shioyama, can you give a rough ETA for the 1.3 release?

**Comment by shioyama** [comment]
Sorry about this, it's been released as 1.3.0.rc1 for now, if there are no issues I'll release the same as 1.3.0 shortly.

**Pull request merged**
