### PR TITLE
ArgumentError: Call `select' with at least one field

### PR DESCRIPTION
**Pull request by dlcmh**
See:
- https://gist.github.com/dlcmh/9879954ec029162b6788640ef250e216
- https://github.com/shioyama/mobility/issues/358

### CODE REVIEW

**Comment by shioyama** [comment]
Hello 👋 Thanks for the PR! Sorry for taking a long time to respond 😅 

Could you rebase on master? I think tests should then pass (or at least not error out). Thanks!

**Comment by thealiilman** [comment]
> Hello 👋 Thanks for the PR! Sorry for taking a long time to respond 😅 
> 
> 
> 
> Could you rebase on master? I think tests should then pass (or at least not error out). Thanks!

Hey Chris, I’ve rebased the PR. Tests are passing. 🙌 @shioyama

**Comment by shioyama** [comment]
Thanks very much! I'll merge and patch to the 0.8.x branch as well when I'm back home, and release a new version with the fix.

**Comment by shioyama** [comment]
Actually, can you add a test for it? So we don't break it in the future.

**Comment by thealiilman** [comment]
> Actually, can you add a test for it? So we don't break it in the future.

Sure, I'll add a test for it. 👍

**Comment by thealiilman** [comment]
@shioyama A test has been written. 🤓

**Comment by shioyama** [comment]
Great, thanks! I'll merge and release later today.

**Comment by thealiilman** [comment]
> Great, thanks! I'll merge and release later today.

Thanks @shioyama for the review and for the great gem! 🙂

**Comment by shioyama** [comment]
This was released in [0.8.11](https://rubygems.org/gems/mobility/versions/0.8.11) :tada:

**Pull request merged**
