### PR TITLE
Avoid referencing ActiveRecord::Base

### PR DESCRIPTION
**Pull request by shioyama**
See: https://github.com/shioyama/mobility/issues/549
Also: https://github.com/bensheldon/good_job_rails7/issues/2

### CODE REVIEW

**Comment by shioyama** [comment]
@leehericks Can you try this branch? It passes all tests, it's just a simple refactor. Happy to ship it, although I'd love to actually understand what is breaking...

**Comment by leehericks** [comment]
@shioyama Can you see any problem?

Screen Shot 2021-12-04 at 10 41 37

**Comment by leehericks** [comment]
@shioyama Yes this does solve the problem.

**Comment by shioyama** [comment]
Released in 1.2.5

**Pull request merged**
