### PR TITLE
Add key, value and belongs_to options to key-value backend

### PR DESCRIPTION
**Pull request by sedubois**
In preparation for #385.

Also see #412.

### CODE REVIEW

**Comment by shioyama** [comment]
Hey wow great work! And fast!!

This looks good, just wondering about the name `translatable`, since it's not really clear what that means without reading the code. Maybe something like `belongs_to_association`?

**Comment by sedubois** [comment]
@shioyama OK translatable has been renamed to belongs_to.

**Comment by shioyama** [comment]
Thanks!! This will go out in v1.1 (soonish).

**Comment by sedubois** [comment]
@shioyama I overlooked these lines in the PR, how to make them use the new options?

https://github.com/shioyama/mobility/blob/b187ad45b5c75c1524c56fd69bdbc222b619e76f/lib/mobility/backends/active_record/key_value.rb#L217-L220

**Comment by shioyama** [comment]
I think it's fine not to go that far. The new columns should be understood to be meant for the case when a different (custom) translation class is used.

**Comment by shioyama** [comment]
This has been released in [1.1.0](https://rubygems.org/gems/mobility/versions/1.1.0) :tada:

**Pull request merged**
