### PR TITLE
Fix uniqueness validation error

### PR DESCRIPTION
**Pull request by jonian**
This fixes issue #33

### CODE REVIEW

**Comment by shioyama** [comment]
Thanks very much! I'm going to enable specs for Rails 5.1+ and see what else is failing. I want to see if this is an issue with query methods in general rather than the uniqueness validator in particular -- if that's the case, I'd prefer to fix the root cause.

**Comment by shioyama** [comment]
I've started running tests against Rails 5.1 in the [active_record_5.x](https://github.com/shioyama/mobility/tree/active_record_5.x) branch, and as expected there are a few issues, many deprecation warnings and some failing specs. I'd like to handle these together, let me have a look and get back to this.

If you want to have a look for yourself, use the branch and `export RAILS_VERSION=5.1` before running specs. There are about 40 failing, I think all with the same thing.

**Comment by shioyama** [comment]
So, as I suspected, this is a problem in Rails 5.1 with `exists?` on queries with translated attributes. There are no actual specs for this method right now but adding one will make this clear.

I'd prefer to fix the root cause (fix `exists?`), so I'm going to investigate that. `present?` converts the query into an array and checks if it is empty, which gets around the problem, so as a quick fix please use it for your project but I'll try to get a proper fix for 5.1 out soon.

**Comment by shioyama** [comment]
Closing this since I fixed the root cause in #36. Thanks again for the PR and the issue!

**Comment by jonian** [comment]
Thanks again for the quick fix!

**Pull request closed without merging**
