### PR TITLE
Add Mobility Action Text to README

### PR DESCRIPTION
**Pull request by sedubois**

### CODE REVIEW

**Comment by sedubois** [comment]
@shioyama I believe the CI failures are not caused by this PR 😄

**Comment by shioyama** [comment]
Oh the build failures are on Rails 6.2 :disappointed:

**Comment by shioyama** [comment]
Oh sorry I fixed those failures in #505 but didn't merge it yet. The fix is in 2a611d6e9e4de64d01c3cf584f13bfc96805abe8, I'll cherry-pick it to master.

**Comment by shioyama** [comment]
Ok cherry-picked it, can you rebase this? Tests should pass.

**Comment by shioyama** [comment]
Hmm ok now there seems to be a different error about `zip`... will look later.

**Comment by shioyama** [comment]
Ok should be fixed if you rebase on master now.

**Comment by sedubois** [comment]
@shioyama there you go.

**Pull request merged**
