### PR TITLE
Enforce case_sensitive comparison for rails 6.1

### LINKED ISSUE #332: Deprecation warning in Rails 6.0.0.rc1 for key attribute in StringTranslation, TextTranslation
## Context
```
mobility (0.8.7)
rails (6.0.0rc1)
```

During specs running it throws warnings

## Expected Behavior
No deprecation warnings

## Actual Behavior
```console
DEPRECATION WARNING: Uniqueness validator will no longer enforce case sensitive comparison in Rails 6.1. To continue case sensitive comparison on the :key attribute in Mobility::ActiveRecord::TextTranslation model, pass `case_sensitive: true` option explicitly to the uniqueness validator. (called from block (2 levels) in <main>

DEPRECATION WARNING: Uniqueness validator will no longer enforce case sensitive comparison in Rails 6.1. To continue case sensitive comparison on the :key attribute in Mobility::ActiveRecord::StringTranslation model, pass `case_sensitive: true` option explicitly to the uniqueness validator. (called from block (2 levels) in <main> 
```
## Possible Fix
```diff
# lib/mobility/active_record/translation.rb
validates :key, presence: true, uniqueness: {
	scope: [:translatable_id, :translatable_type, :locale],
+	case_sensitive: true
}
```

### PR DESCRIPTION
**Pull request by morozRed**
Closes #332

### CODE REVIEW

**Comment by shioyama** [comment]
Thanks!

**Comment by shioyama** [comment]
Saw your message, this was merged into master branch but master has not been released. I can release it on the 0.8.x series, but will have to wait for a bit until I'm back home (traveling for work right now).

**Comment by pacodelaluna** [comment]
Was just going to create an issue about this, my console will appreciate this fix :)

**Comment by shioyama** [comment]
Ok, released as 0.8.10, sorry for the delay!

**Pull request merged**
